### ISSUE TITLE
Can't find world

### ISSUE THREAD

**Issue by edforsberg** [DanielJonssonBH/hello-world#2]
cant find the world object? where is it??

**Comment by edforsberg** [comment]
@DanielJonssonBH still can't see world. Are you even working in this repo??? I need the code to work asap!

**Comment by edforsberg** [comment]
@DanielJonssonBH I don't really trust that this project is going to work if nobody deals with the lack off world. To me, it's a critical feature and it must be dressed first thing before we can continue developing the code further. Please get in touch with me so we can talk this through.

**Comment by DanielJonssonBH** [comment]
The World will never exist, only in your imagination.
